# Generated by Django 5.2.11 on 2026-02-23 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="eventos/"),
        ),
        migrations.AlterField(
            model_name="documento",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="recado",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="DocumentoPrivado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("arquivo", models.FileField(upload_to="documentos_privados/")),
                ("categoria", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Privado",
                "verbose_name_plural": "Documentos Privados",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="EventoPrivado",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=200, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento Privado",
                "verbose_name_plural": "Eventos Privados",
                "ordering": ["data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoAula",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("manha", "Manhã"), ("tarde", "Tarde")], max_length=10
                    ),
                ),
                ("ordem", models.IntegerField(help_text="1º ao 12º período")),
                ("inicio", models.TimeField()),
                ("fim", models.TimeField()),
                (
                    "descricao",
                    models.CharField(
                        blank=True, help_text="Ex: Intervalo, Almoço", max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["turno", "ordem"],
                "unique_together": {("turno", "ordem")},
            },
        ),
        migrations.CreateModel(
            name="RecadoInterno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="recados_internos/"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recado Interno",
                "verbose_name_plural": "Recados Internos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="RegistroFalta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("dia_semana", models.CharField(editable=False, max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("presente", "✅ Presente"),
                            ("atraso", "⏰ Atraso"),
                            ("falta", "❌ Falta"),
                            ("justificada", "📄 Ausência Justificada"),
                        ],
                        default="presente",
                        max_length=20,
                    ),
                ),
                ("hora_chegada", models.TimeField(blank=True, null=True)),
                ("minutos_atraso", models.IntegerField(default=0, editable=False)),
                ("observacao", models.TextField(blank=True)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.periodoaula",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_faltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "periodo__ordem"],
                "unique_together": {("professor", "data", "periodo")},
            },
        ),
    ]
