# Generated by Django 5.2.11 on 2026-02-24 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroPonto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario_previsto_inicio", models.TimeField()),
                ("horario_previsto_fim", models.TimeField()),
                ("entrada_real", models.DateTimeField(blank=True, null=True)),
                ("saida_real", models.DateTimeField(blank=True, null=True)),
                ("observacao", models.TextField(blank=True)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.periodoaula",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ponto",
                "verbose_name_plural": "Registros de Ponto",
                "ordering": ["-data", "periodo__ordem"],
                "unique_together": {("professor", "data", "periodo")},
            },
        ),
    ]
