# Generated by Django 5.2.11 on 2026-02-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_registroponto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrofalta",
            options={"ordering": ["-data"]},
        ),
        migrations.RenameField(
            model_name="registrofalta",
            old_name="hora_chegada",
            new_name="horario_real",
        ),
        migrations.AlterUniqueTogether(
            name="registrofalta",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="registrofalta",
            name="horario_previsto",
            field=models.TimeField(default="07:30"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registrofalta",
            name="turno",
            field=models.CharField(
                choices=[
                    ("manha", "🌅 Manhã"),
                    ("tarde", "☀️ Tarde"),
                    ("integral", "📅 Integral"),
                ],
                default="manha",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="registrofalta",
            name="periodo",
        ),
    ]
