# Generated by Django 5.1.3 on 2026-03-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_registrofalta_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["turma", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10)),
                ("ano", models.IntegerField()),
                ("serie", models.CharField(max_length=20)),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="RegistroFaltaAluno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "quantidade_faltas",
                    models.IntegerField(
                        default=1, help_text="Número de aulas faltadas"
                    ),
                ),
                ("justificada", models.BooleanField(default=False)),
                (
                    "responsavel_contatado",
                    models.CharField(
                        blank=True,
                        help_text="Nome do responsável contatado",
                        max_length=100,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faltas",
                        to="apps.aluno",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faltas_alunos_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Falta de Aluno",
                "verbose_name_plural": "Faltas de Alunos",
                "ordering": ["-data", "aluno__turma", "aluno__numero"],
            },
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="apps.turma",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aluno",
            unique_together={("turma", "numero")},
        ),
    ]
