# Generated by Django 5.1.3 on 2026-03-14 20:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_aluno_turma_registrofaltaaluno_aluno_turma_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroOcorrenciaAluno",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                (
                    "horario_chegada",
                    models.TimeField(verbose_name="Horário de chegada"),
                ),
                (
                    "motivo_alegado",
                    models.TextField(verbose_name="Motivo alegado pelo aluno"),
                ),
                (
                    "atendido_por",
                    models.CharField(
                        max_length=100, verbose_name="Atendido por (pedagoga)"
                    ),
                ),
                (
                    "responsavel_contatado",
                    models.CharField(
                        max_length=100, verbose_name="Nome do responsável contatado"
                    ),
                ),
                (
                    "horario_contato",
                    models.TimeField(verbose_name="Horário do contato"),
                ),
                (
                    "alegado_responsavel",
                    models.TextField(verbose_name="O que foi alegado pelo responsável"),
                ),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="apps.aluno",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência de Aluno",
                "verbose_name_plural": "Ocorrências de Alunos",
                "ordering": ["-data", "-horario_chegada"],
            },
        ),
    ]
