# Generated by Django 5.1.3 on 2026-03-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_registroocorrenciaaluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroocorrenciaaluno",
            name="faltou",
            field=models.BooleanField(default=False, verbose_name="Faltou"),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="horario_chegada",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário de chegada"
            ),
        ),
    ]
