# Generated by Django 5.1.3 on 2026-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_registroocorrenciaaluno_faltou_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="alegado_responsavel",
            field=models.TextField(
                blank=True, verbose_name="O que foi alegado pelo responsável"
            ),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="atendido_por",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Atendido por (pedagoga)"
            ),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="horario_contato",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Horário do contato"
            ),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="motivo_alegado",
            field=models.TextField(
                blank=True, verbose_name="Motivo alegado pelo aluno"
            ),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="responsavel_contatado",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nome do responsável contatado"
            ),
        ),
    ]
