# Generated by Django 5.1.3 on 2026-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_alter_registroocorrenciaaluno_alegado_responsavel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="turno",
            field=models.CharField(
                blank=True,
                choices=[("manha", "Manhã"), ("tarde", "Tarde")],
                max_length=10,
                null=True,
                verbose_name="Turno",
            ),
        ),
    ]
