# Generated by Django 5.1.3 on 2026-03-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_loglogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroocorrenciaaluno",
            name="busca_ativa_realizada",
            field=models.BooleanField(
                default=False, verbose_name="Busca Ativa realizada"
            ),
        ),
    ]
