# Generated by Django 5.1.3 on 2026-04-09 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_registroocorrenciaaluno_busca_ativa_realizada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome social"
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de nascimento"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "email_pessoal",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail pessoal"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("celular", models.CharField(max_length=20, verbose_name="Celular")),
                ("endereco", models.TextField(blank=True, verbose_name="Endereço")),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "disciplinas",
                    models.TextField(blank=True, verbose_name="Disciplinas lecionadas"),
                ),
                (
                    "formacao",
                    models.TextField(blank=True, verbose_name="Formação acadêmica"),
                ),
                (
                    "data_admissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de admissão"
                    ),
                ),
                (
                    "carga_horaria",
                    models.IntegerField(
                        default=40, verbose_name="Carga horária semanal"
                    ),
                ),
                (
                    "curriculo",
                    models.FileField(blank=True, null=True, upload_to="curriculos/"),
                ),
                (
                    "documento_identidade",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos_professores/"
                    ),
                ),
                (
                    "comprovante_residencia",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos_professores/"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário (login)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["nome_completo"],
            },
        ),
    ]
