# Generated by Django 5.1.3 on 2026-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_professor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="celular",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Celular"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="E-mail"
            ),
        ),
    ]
