# Generated by Django 5.2.11 on 2026-04-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_alter_professor_celular_alter_professor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroocorrenciaaluno",
            name="tipo_ocorrencia",
            field=models.CharField(
                choices=[
                    ("falta", "Falta"),
                    ("atraso", "Atraso"),
                    ("justificada", "Justificada"),
                ],
                default="falta",
                max_length=20,
                verbose_name="Tipo de ocorrência",
            ),
        ),
    ]
