# Generated by Django 5.2.11 on 2026-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_registroocorrenciaaluno_tipo_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroocorrenciaaluno",
            name="observacoes_adicionais",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações Adicionais (ATA)"
            ),
        ),
        migrations.AlterField(
            model_name="registroocorrenciaaluno",
            name="tipo_ocorrencia",
            field=models.CharField(
                choices=[
                    ("falta", "Falta"),
                    ("atraso", "Atraso"),
                    ("piercing", "Uso de Piercing"),
                    ("cabelo", "Cabelo"),
                    ("uniforme", "Uniforme"),
                    ("desvio_normas", "Desvio de Normas"),
                ],
                default="falta",
                max_length=20,
                verbose_name="Tipo de ocorrência",
            ),
        ),
    ]
