# Generated by Django 5.2.11 on 2026-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_registroocorrenciaaluno_observacoes_adicionais_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroocorrenciaaluno",
            name="turno",
            field=models.CharField(
                choices=[("manha", "Manhã"), ("tarde", "Tarde")],
                default="manha",
                max_length=10,
                verbose_name="Turno",
            ),
        ),
    ]
