# Generated by Django 5.2.13 on 2026-04-17 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0017_registroocorrenciaaluno_turno"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=10, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("fixo", "Fixo - Turma inteira"),
                            ("itinerante", "Itinerante - Equipamentos avulsos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipamento", models.CharField(max_length=30)),
                (
                    "quantidade_total",
                    models.IntegerField(
                        default=0,
                        help_text="Para itinerantes: 50 tablets, 30 celulares",
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemEquipamento",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("patrimonio", models.CharField(blank=True, max_length=50)),
                ("disponivel", models.BooleanField(default=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="apps.laboratorio",
                    ),
                ),
            ],
            options={
                "unique_together": {("laboratorio", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_emprestimo",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("aluno", "Aluno"),
                            ("turma", "Turma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("data_emprestimo", models.DateTimeField(auto_now_add=True)),
                ("data_prevista_devolucao", models.DateField()),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("motivo", models.TextField()),
                ("aulas_utilizacao", models.CharField(blank=True, max_length=50)),
                ("observacao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emprestado", "Emprestado"),
                            ("devolvido", "Devolvido"),
                            ("atrasado", "Atrasado"),
                        ],
                        default="emprestado",
                        max_length=20,
                    ),
                ),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apps.aluno",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apps.professor",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apps.turma",
                    ),
                ),
                (
                    "itens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="emprestimos",
                        to="apps.itemequipamento",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "itinerante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.laboratorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgendamentoLab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("1", "1ª Aula"),
                            ("2", "2ª Aula"),
                            ("3", "3ª Aula"),
                            ("4", "4ª Aula"),
                            ("5", "5ª Aula"),
                            ("6", "6ª Aula"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("manha", "Manhã"), ("tarde", "Tarde")], max_length=5
                    ),
                ),
                ("disciplina", models.CharField(max_length=100)),
                ("observacao", models.TextField(blank=True)),
                ("registrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.professor"
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.turma"
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "fixo"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.laboratorio",
                    ),
                ),
            ],
            options={
                "unique_together": {("laboratorio", "data", "horario", "turno")},
            },
        ),
    ]
