# Generated by Django 5.2.13 on 2026-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0018_laboratorio_itemequipamento_emprestimo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
    ]
