# Generated by Django 6.0.2 on 2026-04-26 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_registroocorrenciaaluno_resposta_disparo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitadorTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digitadores', to='apps.turma', verbose_name='Turma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turma_digitador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário digitador')),
            ],
            options={
                'verbose_name': 'Vínculo de digitador com turma',
                'verbose_name_plural': 'Vínculos de digitadores com turmas',
            },
        ),
    ]
